[build]
  command = "npm run build"
  publish = "dist"
  base = "frontend"

[functions]
  directory = "frontend/backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
